module.exports = Object.freeze({
	TEMA_NO_ENCONTRADO        : 'Tema no encontrado',
	TEMA_YA_EXISTE            : 'El tema ya existe',
	TEMA_REGISTRADO           : 'Nuevo tema registrado con éxito',
	TEMA_ACTUALIZADO          : 'Tema actualizado con éxito',
	FABRICANTE_NO_ENCONTRADO  : 'Fabricante no encontrado',
	FABRICANTE_YA_EXISTE      : 'El fabricante ya existe',
	FABRICANTE_REGISTRADO     : 'Nuevo fabricante registrado con éxito',
	FABRICANTE_ACTUALIZADO    : 'Fabricante actualizado con éxito',
	EDITORIAL_NO_ENCONTRADA   : 'Editorial no encontrada',
	EDITORIAL_YA_EXISTE       : 'La editorial ya existe',
	EDITORIAL_REGISTRADA      : 'Nueva editorial registrada con éxito',
	EDITORIAL_ACTUALIZADA     : 'Editorial actualizada con éxito',
	IDIOMA_NO_ENCONTRADO      : 'Idioma no encontrado',
	IDIOMA_YA_EXISTE          : 'El idioma ya existe',
	IDIOMA_REGISTRADO         : 'Nuevo idioma registrado con éxito',
	IDIOMA_ACTUALIZADO        : 'Idioma actualizado con éxito',
	ENLACE_NO_ENCONTRADO      : 'Enlace no encontrado',
	ENLACE_REGISTRADO         : 'Nuevo enlace registrado con éxito',
	ENLACE_ACTUALIZADO        : 'Enlace actualizado con éxito',
	ENLACE_BORRADO            : 'Enlace borrado con éxito',
	TITULO_REQUERIDO 	  	  : 'El título es un campo requerido',
	URL_FORMATO_INCORRECTO    : 'La url no tiene el formato esperado',
	NOMBRE_REQUERIDO 	  	  : 'El nombre es un campo requerido',
	NOMBRE_MIN_LENGTH_3 	  : 'El nombre debe tener al menos 3 caracteres',
	PARAMETRO_ID_INCORRECTO   : 'El parámetro indicado es incorrecto',
	LIBRO_NO_ENCONTRADO	      : 'Libro no encontrado',
	LIBRO_REGISTRADO          : 'Nuevo libro registrado con éxito',
	LIBRO_ACTUALIZADO         : 'Libro actualizado con éxito',
	LIBRO_BORRADO             : 'Libro borrado con éxito',
	TUTORIAL_NO_ENCONTRADO    : 'Tutorial no encontrado',
	TUTORIAL_REGISTRADO       : 'Nuevo tutorial registrado con éxito',
	TUTORIAL_ACTUALIZADO      : 'Tutorial actualizado con éxito',
	TUTORIAL_BORRADO          : 'Tutorial borrado con éxito',
	AÑO_PUBLICACION_NO_VALIDO : 'Año de publiación no válido',
	PAGINAS_NO_VALIDO 		  : 'Número de páginas no válido'
});